name: Android CI (Debug APK)

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Android SDK + tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install platforms/build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "cmdline-tools;latest"

      - name: Write local.properties (point Gradle to SDK)
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      # ---- MANUAL GRADLE INSTALL (no cache) ----
      - name: Install Gradle 8.7
        run: |
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Make wrapper executable
        run: chmod +x ./gradlew

      # Build the debug APK (verbose) + capture log
      - name: Build Debug APK (verbose)
        run: |
          set -o pipefail
          ./gradlew --no-daemon --stacktrace --info assembleDebug | tee buildlog.txt

      - name: Upload build log
        if: always()
        uses: actions/upload-
